AllCops:
  Exclude:
    - 'spec/**/*'
  TargetRubyVersion: 2.3.1

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 20

FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
